name: SonarQube And Eslint Code Checked
on:
  pull_request:
    branches:   
      - main
  workflow_dispatch: 
jobs:
  code-unit-testing:
    name: Clean Code Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Develop
      uses: actions/checkout@v3

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Code Quality
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      continue-on-error: true
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Eslint clean code check
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install
    - uses: sibiraj-s/action-eslint@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,jsx,ts,tsx'
        annotations: true